# Generated by Django 4.2.5 on 2023-10-02 08:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_animal', models.CharField(max_length=200)),
                ('photo_animal', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('Sexe', models.CharField(max_length=200)),
                ('date_de_naissance', models.DateField()),
                ('élément', models.CharField(max_length=200)),
                ('type_animal', models.CharField(max_length=200)),
                ('status_animal', models.CharField(max_length=200)),
                ('sterilisé', models.BooleanField()),
                ('suivi_par_professionnel', models.BooleanField()),
                ('régime_alimentaire', models.CharField(max_length=200)),
                ('compléments_aliménetaires', models.CharField(max_length=200)),
                ('traitements_médicaux', models.CharField(max_length=200)),
                ('antécédents_médicaux', models.CharField(max_length=200)),
                ('résumé', models.TextField()),
            ],
            options={
                'verbose_name': 'Animal',
                'ordering': ['nom_animal'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prénom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('téléphone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='FR')),
                ('adresse', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('réservé_le', models.DateTimeField(auto_now_add=True)),
                ('prix_séance', models.IntegerField()),
                ('séance_payée', models.BooleanField()),
                ('séance_payée_le', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.animal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['date_creation'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
        migrations.AddField(
            model_name='animal',
            name='propriétaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
    ]
