# Generated by Django 4.2.5 on 2023-10-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_animal_rendezvous_user_delete_article_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='client',
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='RendezVous',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
